// Files generated by MCC 
#include "mcc_generated_files/system.h"
#include "helper_funcs.c"

int main(void)
{
    // initialize the device
    SYSTEM_Initialize(); 

    uint flag = 0;
    
    TRISEbits.TRISE0 = 0;
    TRISBbits.TRISB14 = 0;

    LATEbits.LATB14 = 0;
    LATEbits.LATE0 = 0; 

    while (1)
    {
        t++;
        if(t==50000)
        {
            t = 0;
            LATEbits.LATE0 = !LATEbits.LATE0; // Blink led on RB6
        }
    }

}

