// Files generated by MCC 
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>

#include "mcc_generated_files/system.h"
#include "helper_funcs.c"
#include "leds.h"
#include "buttons.h"
#include "buttons.c"
#include "timer_1ms.c"
#include "timer_1ms.h"
#include "adc.c"
#include "adc.h"

#define BUTTON_DEBOUNCE_TIME 25000

//------------------------------------------------------------------------------
//Global variables
//------------------------------------------------------------------------------
static volatile BUTTON_COLOR buttonColor = BUTTON_COLOR_RED;


int main(void)
{
    // initialize the device
    SYSTEM_Initialize(); 

    // Enable buttons as inputs
    BUTTON_Enable(BUTTON_S1);

    // Set the time
    TIMER_SetConfiguration(TIMER_CONFIGURATION_1MS);

    //Enable and configure the ADC so it can sample the potentiometer.
    ADC_SetConfiguration(ADC_CONFIGURATION_DEFAULT);
    ADC_ChannelEnable(ADC_CHANNEL_POTENTIOMETER);

    FLAGS flags;
    flags.all_flags = 0; // Set all flags to zero

    uint16_t potentiometer = 0;

    // Set PWM pins as output
    TRISBbits.TRISB11 = 0;
    TRISBbits.TRISB10 = 0;
    TRISCbits.TRISC4  = 0;
    TRISCbits.TRISC10 = 0;

    PWM_GENERATOR pwm4 = PWM_GENERATOR_4;
    PWM_GENERATOR pwm3 = PWM_GENERATOR_3;
    PWM_GENERATOR pwm2 = PWM_GENERATOR_2;
    PWM_GENERATOR pwm1 = PWM_GENERATOR_1; // Instantiate PGs
    CLK_RATIO     clk  = ONE_FOUR; // Set the clock divison ratio for PWM

    set_PWM_CLK_DIV(clk); // Enable the clock divison circuit

    config_PWM(pwm4, 0xFFEF, 0xBFF4, 0xFFF0); // Configure DC, PHASE, PER (in that order)
    enable_PWM_CLK_DIV(pwm4); // Enable clock divison 

    config_PWM(pwm3, 0xBFF4, 0x7FF8, 0xFFF0);
    enable_PWM_CLK_DIV(pwm3); // Enable clock divison 

    config_PWM(pwm2, 0x7FF8, 0x3FFC, 0xFFF0);
    enable_PWM_CLK_DIV(pwm2); // Enable clock divison 

    config_PWM(pwm1, 0x7FF8, 0x00, 0xFFF0);
    enable_PWM_CLK_DIV(pwm1); // Enable clock divison 

    PWM_ModuleEnable(pwm1);
    PWM_ModuleEnable(pwm2);
    PWM_ModuleEnable(pwm3);
    PWM_ModuleEnable(pwm4);


    while (1)
    {
        lib_blink(&flags);
        
        if(BUTTON_IsPressed(BUTTON_S1) == 1){
            // Debounce
            lib_stall(BUTTON_DEBOUNCE_TIME); // Wait
            flags.btn_pressed = BUTTON_IsPressed(BUTTON_S1) == 1; // Button still pressed?
            flags.reliable = flags.btn_pressed == 1; 
            if(!flags.reliable) flags.btn_pressed = 0;

            flags.toggle = !flags.toggle;
            PIN_D9 = flags.toggle; 
        }

        potentiometer = ADC_ReadPercentage(ADC_CHANNEL_POTENTIOMETER);
        set_RGB_LED(potentiometer);
    }

}
