// Files generated by MCC 
#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>

#include "mcc_generated_files/system.h"
#include "helper_funcs.c"
#include "leds.h"
#include "buttons.h"
#include "buttons.c"
#include "timer_1ms.c"
#include "timer_1ms.h"
#include "adc.c"
#include "adc.h"
#include "pwm.h"

#define BUTTON_DEBOUNCE_TIME 15000

//------------------------------------------------------------------------------
//Global variables
//------------------------------------------------------------------------------
static volatile BUTTON_COLOR buttonColor = BUTTON_COLOR_RED;


int main(void)
{
    // initialize the device
    SYSTEM_Initialize(); 

    // Enable buttons as inputs
    BUTTON_Enable(BUTTON_S1);

    // Set the time
    TIMER_SetConfiguration(TIMER_CONFIGURATION_1MS);

    //Enable and configure the ADC so it can sample the potentiometer.
    ADC_SetConfiguration(ADC_CONFIGURATION_DEFAULT);
    ADC_ChannelEnable(ADC_CHANNEL_POTENTIOMETER);

    FLAGS flags;
    flags.all_flags = 0; // Set all flags to zero

    uint16_t potentiometer = 0;

    // PWM Module 
    PWM_GENERATOR pwm3 = PWM_GENERATOR_3;

    PWM_MasterDutyCycleSet(0xFFF0>>2);
    PWM_MasterPeriodSet(0xFFF0);
    PWM_MasterPhaseSet(0xFFFF);
    PWM_ModuleEnable(pwm3);

    while (1)
    {
        lib_blink(&flags);
        
        if(BUTTON_IsPressed(BUTTON_S1) == 1){
            // Debounce
            lib_stall(BUTTON_DEBOUNCE_TIME); // Wait
            flags.btn_pressed = BUTTON_IsPressed(BUTTON_S1) == 1; // Button still pressed?
            flags.reliable = flags.btn_pressed == 1; 
            if(!flags.reliable) flags.btn_pressed = 0;

            flags.toggle = !flags.toggle;
            PIN_D9 = flags.toggle; 
        }

        potentiometer = ADC_ReadPercentage(ADC_CHANNEL_POTENTIOMETER);
        set_RGB_LED(potentiometer);
    }

}
